/**
 * CCV verifier gRPC schema, as a committed protobufjs JSON descriptor.
 *
 * GENERATED by `ccip-sdk/scripts/gen-verifier-descriptor.mjs` from `src/verifiers/proto/*.proto`.
 * DO NOT EDIT BY HAND. Regenerate when the `.proto` files change.
 *
 * Loading this object with `protobuf.Root.fromJSON` is browser-safe: it performs no filesystem or
 * `.proto` read, unlike `@grpc/proto-loader`'s runtime `loadSync`.
 *
 * @packageDocumentation
 */
import type { INamespace } from 'protobufjs'

/** protobufjs JSON descriptor for `chainlink_ccv.verifier.v1` and its `google.rpc` dependency. */
export const verifierProtoDescriptor: INamespace = {
  nested: {
    chainlink_ccv: {
      nested: {
        verifier: {
          nested: {
            v1: {
              options: {
                go_package:
                  'github.com/smartcontractkit/chainlink-protos/chainlink-ccv/verifier/v1',
              },
              nested: {
                Verifier: {
                  methods: {
                    GetVerifierResultsForMessage: {
                      requestType: 'GetVerifierResultsForMessageRequest',
                      responseType: 'GetVerifierResultsForMessageResponse',
                      comment: '',
                    },
                  },
                },
                GetVerifierResultsForMessageRequest: {
                  fields: {
                    message_ids: {
                      rule: 'repeated',
                      type: 'bytes',
                      id: 1,
                    },
                  },
                },
                GetVerifierResultsForMessageResponse: {
                  fields: {
                    results: {
                      rule: 'repeated',
                      type: 'VerifierResult',
                      id: 1,
                    },
                    errors: {
                      rule: 'repeated',
                      type: 'google.rpc.Status',
                      id: 2,
                    },
                  },
                },
                Message: {
                  fields: {
                    sender: {
                      type: 'bytes',
                      id: 1,
                    },
                    data: {
                      type: 'bytes',
                      id: 2,
                    },
                    on_ramp_address: {
                      type: 'bytes',
                      id: 3,
                    },
                    token_transfer: {
                      type: 'bytes',
                      id: 4,
                    },
                    off_ramp_address: {
                      type: 'bytes',
                      id: 5,
                    },
                    dest_blob: {
                      type: 'bytes',
                      id: 6,
                    },
                    receiver: {
                      type: 'bytes',
                      id: 7,
                    },
                    source_chain_selector: {
                      type: 'uint64',
                      id: 8,
                    },
                    dest_chain_selector: {
                      type: 'uint64',
                      id: 9,
                    },
                    sequence_number: {
                      type: 'uint64',
                      id: 10,
                    },
                    execution_gas_limit: {
                      type: 'uint32',
                      id: 11,
                    },
                    ccip_receive_gas_limit: {
                      type: 'uint32',
                      id: 12,
                    },
                    finality: {
                      type: 'uint32',
                      id: 13,
                    },
                    ccv_and_executor_hash: {
                      type: 'bytes',
                      id: 14,
                    },
                    dest_blob_length: {
                      type: 'uint32',
                      id: 15,
                    },
                    token_transfer_length: {
                      type: 'uint32',
                      id: 16,
                    },
                    data_length: {
                      type: 'uint32',
                      id: 17,
                    },
                    receiver_length: {
                      type: 'uint32',
                      id: 18,
                    },
                    sender_length: {
                      type: 'uint32',
                      id: 19,
                    },
                    version: {
                      type: 'uint32',
                      id: 20,
                    },
                    off_ramp_address_length: {
                      type: 'uint32',
                      id: 21,
                    },
                    on_ramp_address_length: {
                      type: 'uint32',
                      id: 22,
                    },
                  },
                },
                VerifierResult: {
                  fields: {
                    message: {
                      type: 'Message',
                      id: 1,
                    },
                    message_ccv_addresses: {
                      rule: 'repeated',
                      type: 'bytes',
                      id: 2,
                    },
                    message_executor_address: {
                      type: 'bytes',
                      id: 3,
                    },
                    ccv_data: {
                      type: 'bytes',
                      id: 4,
                    },
                    metadata: {
                      type: 'VerifierResultMetadata',
                      id: 5,
                    },
                  },
                },
                VerifierResultMetadata: {
                  fields: {
                    timestamp: {
                      type: 'int64',
                      id: 1,
                    },
                    verifier_source_address: {
                      type: 'bytes',
                      id: 2,
                    },
                    verifier_dest_address: {
                      type: 'bytes',
                      id: 3,
                    },
                  },
                },
              },
            },
          },
        },
      },
    },
    google: {
      nested: {
        protobuf: {
          nested: {
            Any: {
              fields: {
                type_url: {
                  type: 'string',
                  id: 1,
                },
                value: {
                  type: 'bytes',
                  id: 2,
                },
              },
            },
          },
        },
        rpc: {
          options: {
            go_package: 'google.golang.org/genproto/googleapis/rpc/status;status',
          },
          nested: {
            Status: {
              fields: {
                code: {
                  type: 'int32',
                  id: 1,
                },
                message: {
                  type: 'string',
                  id: 2,
                },
                details: {
                  rule: 'repeated',
                  type: 'google.protobuf.Any',
                  id: 3,
                },
              },
            },
          },
        },
      },
    },
  },
}
