#!/bin/sh

SCRIPT_DIR="$(CDPATH="" cd -P "$(dirname -- "$0")" && pwd -P)"
NODE_VERSION="$(node --version | sed 's/v//' | cut -d'.' -f1)"

export CLI_NAME="$(basename -- "$0")"

if [ ! -f "$SCRIPT_DIR/src/index.ts" ]; then
  exec node "$SCRIPT_DIR/dist/index.js" "$@"
elif [ "$NODE_VERSION" -ge 23 ]; then
  exec node "$SCRIPT_DIR/src/index.ts" "$@"
else
  exec npx tsx "$SCRIPT_DIR/src/index.ts" "$@"
fi
