import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

import { exampleRepos } from './src/config/examples.config.ts'

const activeExample = exampleRepos.find((r) => r.status === 'active')

/**
 * SDK Documentation Sidebar
 * Auto-generated from TypeDoc with custom overview
 */
const sidebars: SidebarsConfig = {
  sdkSidebar: [
    {
      type: 'doc',
      id: 'introduction',
      label: 'Overview',
    },
    ...(activeExample
      ? [
          {
            type: 'link' as const,
            label: activeExample.title,
            href: activeExample.repoUrl,
          },
        ]
      : []),
    {
      type: 'category',
      label: 'Guides',
      collapsed: false,
      items: [
        'guides/tracking-messages',
        'guides/searching-messages',
        'guides/sending-messages',
        'guides/pre-send-validation',
        'guides/manual-execution',
        'guides/querying-data',
        {
          type: 'category',
          label: 'Cross-Chain Tokens',
          collapsed: false,
          items: [
            'guides/cct/overview',
            'guides/cct/evm',
            'guides/cct/solana',
            'guides/cct/canton',
            {
              type: 'category',
              label: 'Reference',
              collapsed: false,
              items: [
                'guides/cct/reference/pool-types',
                'guides/cct/reference/inspecting-pools',
                'guides/cct/reference/inspecting-registry',
                'guides/cct/reference/inspecting-tokens',
                'guides/cct/reference/verify-your-setup',
                'guides/cct/reference/advanced-pool-hooks',
              ],
            },
          ],
        },
        'guides/multi-chain',
        'guides/chain-endpoints',
        'guides/viem-integration',
        'guides/browser-setup',
        'guides/error-handling',
        'guides/error-reference',
        'guides/json-integer-precision',
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      collapsed: false,
      link: {
        type: 'doc',
        id: 'api-reference',
      },
      items: [
        {
          type: 'category',
          label: 'classes',
          items: [{ type: 'autogenerated', dirName: 'classes' }],
        },
        {
          type: 'category',
          label: 'functions',
          items: [{ type: 'autogenerated', dirName: 'functions' }],
        },
        {
          type: 'category',
          label: 'interfaces',
          items: [{ type: 'autogenerated', dirName: 'interfaces' }],
        },
        {
          type: 'category',
          label: 'type-aliases',
          items: [{ type: 'autogenerated', dirName: 'type-aliases' }],
        },
        {
          type: 'category',
          label: 'variables',
          items: [{ type: 'autogenerated', dirName: 'variables' }],
        },
      ],
    },
  ],
}

export default sidebars
