import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

/**
 * SDK Documentation Sidebar
 * Auto-generated from TypeDoc with custom overview
 */
const sidebars: SidebarsConfig = {
  sdkSidebar: [
    {
      type: 'doc',
      id: 'introduction',
      label: 'Overview',
    },
    {
      type: 'category',
      label: 'Guides',
      collapsed: false,
      items: [
        'guides/tracking-messages',
        'guides/sending-messages',
        'guides/manual-execution',
        'guides/querying-data',
        'guides/token-pools',
        'guides/multi-chain',
        'guides/viem-integration',
        'guides/browser-setup',
        'guides/error-handling',
        'guides/error-reference',
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      collapsed: false,
      link: {
        type: 'doc',
        id: 'api-reference',
      },
      items: [
        {
          type: 'category',
          label: 'classes',
          items: [{ type: 'autogenerated', dirName: 'classes' }],
        },
        {
          type: 'category',
          label: 'functions',
          items: [{ type: 'autogenerated', dirName: 'functions' }],
        },
        {
          type: 'category',
          label: 'interfaces',
          items: [{ type: 'autogenerated', dirName: 'interfaces' }],
        },
        {
          type: 'category',
          label: 'type-aliases',
          items: [{ type: 'autogenerated', dirName: 'type-aliases' }],
        },
        {
          type: 'category',
          label: 'variables',
          items: [{ type: 'autogenerated', dirName: 'variables' }],
        },
      ],
    },
  ],
}

export default sidebars
