/**
 * Type stub for OpenAPI-generated sidebar.
 * The actual sidebar.ts file is generated by docusaurus-plugin-openapi-docs during build.
 * This declaration provides types for TypeScript checking before the file is generated.
 */
import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

type SidebarItems = NonNullable<SidebarsConfig[string]>
declare const items: SidebarItems
export default items
