name: Publish Package

on:
  push:
    branches:
      - develop
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.17.0'
      - run: npm ci
      - run: npm run lint --if-present
      - run: npm run build --if-present
